
name: CI/CD
on:
  push: 
  repository_dispatch:
    types:
      - resource-base-updated
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get ResourceBase version
        id: resourcebase
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "version=${{ github.event.client_payload.resource_base_version }}" >> "$GITHUB_OUTPUT"
          else
            echo "version=" >> "$GITHUB_OUTPUT"
          fi
