
name: CI/CD
on:
  push: 
  repository_dispatch:
    types:
      - resource-base-updated
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get ResourceBase version
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          VERSION="${{ github.event.client_payload.resource_base_version }}"
          echo "ResourceBase version: $VERSION"
      
      - name: Update pom.xml
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          VERSION="${{ github.event.client_payload.resource_base_version }}"
      
          mvn versions:set \
            -DnewVersion="$VERSION" \
            -DgenerateBackupPoms=false
      
          echo "Updated pom.xml:"
          grep -n "<version>" pom.xml
      - name: Commit and push
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          git add pom.xml
      
          git diff --cached
      
          git commit -m "Update ResourceBase version" || echo "No changes to commit"
      
          git push
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Dummy Deploy
      run: |
        echo "Deploying HAPI application..."
        echo "Deployment completed successfully."
