
name: CI/CD
on:
  push: 
  repository_dispatch:
    types:
      - resource-base-updated
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get ResourceBase version
        run: |
          VERSION="${{ github.event.client_payload.resource_base_version }}"
          echo "ResourceBase version: $VERSION"
      
      - name: Update pom.xml
        run: |
          VERSION="${{ github.event.client_payload.resource_base_version }}"
      
          mvn versions:set \
            -DnewVersion="$VERSION" \
            -DgenerateBackupPoms=false
      
          echo "Updated pom.xml:"
          grep -n "<version>" pom.xml
